### ISSUE TITLE
Wandboard support

### ISSUE THREAD

**Issue by e630193** [TechNexion/u-boot-tn-imx#44]
make wandboard_defconfig
make
In file included from include/config.h:3:
include/configs/wandboard.h:13:10: fatal error: imx6_spl.h: No such file or directory

What, with the lack of Fairy board support too, is this repo meant to be functional?

**Comment by ray-chang** [comment]
@e630193 

Thank you for the feedback.


If you are using a Fairy board, please use `edm-imx6_spl_defconfig` for compilation. The `wandboard_defconfig` is intended for the Wandboard, which is primarily maintained by the open-source community. Please note that the Wandboard code maintained by TN is currently based on version v2022.04. 
https://github.com/TechNexion/u-boot-tn-imx/tree/tn-imx_v2022.04_5.15.71_2.2.0-stable

Regarding the hardware, while the i.MX6 product longevity extends until 2030, we highly recommend selecting a newer SoC generation for new product developments to ensure long-term availability beyond that date.

BR,
Ray

**Comment by e630193** [comment]
I support both Wandboard and Fairy. I was using wandboard_defconfig to build for the Wandboard on this occasion and I get the imx6_spl.h missing error.

Regarding the hardware, I'm also attempting to support the Fairy board deployed as IoT cellular router but it's stuck on v4.1.15 kernel because of lack of devicetree support and I'm not a devicetree expert. The Fairy boards were purchased with original SOM that came with broadcom wifi and the DTBs built today do not fully work. I do not need wifi but support for pcie slots does not work with current dtb (latest Technexion kernel trees).

Are there any dts/dtsi files that support these original bcm SOM so that I can get pcie working?

**Comment by ray-chang** [comment]
@e630193 

We've addressed the compilation error for `wandboard_defconfig`. Please be aware that this fix has only been verified to compile and has not undergone full functional testing yet.
https://github.com/TechNexion/u-boot-tn-imx/commit/d7aa9e72c8ef59511c004f3b0f03fe88115037fb

For PCIe functionality, you may consider using the device tree with the -qca suffix (provided the Wi-Fi module is not a concern for your setup). We continue to maintain and test this version.

Additionally, our verification team has verified that PCIe works correctly on Kernel versions 6.6 and 6.12.

**Comment by e630193** [comment]
Okay, thank you for the help and information.
